from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from store.models import Category, Phone


class Command(BaseCommand):
    help = 'Seed database with 100+ phones across all categories'

    def handle(self, *args, **kwargs):
        if not User.objects.filter(username='admin').exists():
            User.objects.create_superuser('admin', 'admin@phoneshop.com', 'admin123')
            self.stdout.write(self.style.SUCCESS('Created admin user (admin/admin123)'))
        if not User.objects.filter(username='testuser').exists():
            User.objects.create_user('testuser', 'test@phoneshop.com', 'test123')
            self.stdout.write(self.style.SUCCESS('Created test user (testuser/test123)'))

        categories_data = [
            ('Flagship',    'Top-of-the-line premium smartphones'),
            ('Mid-Range',   'Best value for money smartphones'),
            ('Budget',      'Affordable smartphones for everyone'),
            ('Foldable',    'Next-gen foldable smartphones'),
            ('Gaming',      'High-performance smartphones built for gaming'),
            ('Rugged',      'Tough phones built for extreme conditions'),
        ]
        categories = {}
        for name, desc in categories_data:
            cat, _ = Category.objects.get_or_create(name=name, defaults={'description': desc})
            categories[name] = cat
        self.stdout.write(f'Categories ready: {len(categories)}')

        IMG = {
            'apple':    'https://cdsassets.apple.com/live/7WUAS350/images/iphone/iphone-17-pro-max-colors.png?w=400',
            'apple2':   'https://object.pscloud.io/cms/cms/Photo/img_0_77_5124_0_1_ib45Xi.webp?w=400',
            'apple3':   'https://api.technodom.kz/f3/api/v1/images/800/800/265299_1v.jpg?w=400',
            'samsung':  'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400',
            'samsung2': 'https://images.unsplash.com/photo-1567581935884-3349723552ca?w=400',
            'samsung3': 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400',
            'samsung4': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPTzXUe5OxI3gBCOPMCkoxIhlZ-JvLExnUmQ&s?w=400',
            'google':   'https://lh3.googleusercontent.com/LDj3-pgnVeoxCjF0FbgMAXHFZdqTNIIdET1MWMSwn1xcGC9lzI8zQwVSMWkjuw52ucZ1K8_HyhKMrBQcE5cE7ZEBZFbPV8vJGTZvUw=e365-pa-nu-s0?w=400',
            'xiaomi':   'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400',
            'oneplus':  'https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=400',
            'generic':  'https://m.media-amazon.com/images/I/61KJVZetzXL._AC_UF894,1000_QL80_.jpg?w=400',
            'generic2': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEq7b5NUswb1bIwqf89Y7Nz-sqWw5Wli-OaA&s?w=400',
            'generic3': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400',
            'rugged':   'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4hSDEoa7QO_jHAW9J85o2Bw9GSXp-jCHOlA&s?w=400',
            'gaming':   'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhe9Q23TIAc16XWvRykuJrbZQJvqe_u5mJbg&s?w=400',
        }

        phones_data = [
            {'category': categories['Flagship'], 'brand': 'Apple',   'name': 'iPhone 16 Pro Max',    'model': '16 Pro Max',    'price': 1299.99, 'stock': 25, 'ram': '8GB',  'storage': '256GB', 'battery': '4685mAh', 'camera': '48MP Triple',  'image_url': IMG['apple'],   'description': 'The most powerful iPhone ever. A18 Pro chip, 48MP Fusion camera system, titanium design, and Action Button.'},
            {'category': categories['Flagship'], 'brand': 'Apple',   'name': 'iPhone 16 Pro',        'model': '16 Pro',        'price': 1099.99, 'stock': 30, 'ram': '8GB',  'storage': '128GB', 'battery': '3274mAh', 'camera': '48MP Triple',  'image_url': IMG['apple2'],  'description': 'Pro-level performance in a compact form. A18 Pro chip, ProMotion 120Hz display, and USB-C with USB 3 speeds.'},
            {'category': categories['Flagship'], 'brand': 'Apple',   'name': 'iPhone 15 Pro Max',    'model': '15 Pro Max',    'price':  999.99, 'stock': 20, 'ram': '8GB',  'storage': '256GB', 'battery': '4422mAh', 'camera': '48MP Triple',  'image_url': IMG['apple3'],  'description': 'Previous-gen titanium flagship. A17 Pro chip, periscope telephoto lens, and USB-C connectivity.'},
            {'category': categories['Flagship'], 'brand': 'Samsung', 'name': 'Galaxy S25 Ultra',     'model': 'S25 Ultra',     'price': 1199.99, 'stock': 28, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '200MP Quad',   'image_url': IMG['samsung'], 'description': 'Samsung\'s ultimate flagship. Snapdragon 8 Elite, built-in S Pen, 200MP quad camera, and 6.9-inch Dynamic AMOLED display.'},
            {'category': categories['Flagship'], 'brand': 'Samsung', 'name': 'Galaxy S25+',          'model': 'S25+',          'price':  999.99, 'stock': 35, 'ram': '12GB', 'storage': '256GB', 'battery': '4900mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung2'],'description': 'Large-screen flagship with Snapdragon 8 Elite, 6.7-inch display, and all-day battery life.'},
            {'category': categories['Flagship'], 'brand': 'Samsung', 'name': 'Galaxy S25',           'model': 'S25',           'price':  799.99, 'stock': 40, 'ram': '12GB', 'storage': '128GB', 'battery': '4000mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung3'],'description': 'The standard Galaxy S25. Compact, powerful, with Snapdragon 8 Elite and a stunning 6.2-inch display.'},
            {'category': categories['Flagship'], 'brand': 'Samsung', 'name': 'Galaxy S24 Ultra',     'model': 'S24 Ultra',     'price':  999.99, 'stock': 15, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '200MP Quad',   'image_url': IMG['samsung4'],'description': 'Last-gen Ultra flagship. Snapdragon 8 Gen 3, integrated S Pen stylus, titanium frame, and 100x Space Zoom.'},
            {'category': categories['Flagship'], 'brand': 'Google',  'name': 'Pixel 9 Pro XL',       'model': '9 Pro XL',      'price': 1099.99, 'stock': 18, 'ram': '16GB', 'storage': '128GB', 'battery': '5060mAh', 'camera': '50MP Triple',  'image_url': IMG['google'],  'description': 'Google\'s largest Pro phone. Tensor G4 chip, 6.8-inch LTPO display, 7 years of OS updates, and AI-powered photography.'},
            {'category': categories['Flagship'], 'brand': 'Google',  'name': 'Pixel 9 Pro',          'model': '9 Pro',         'price':  999.99, 'stock': 22, 'ram': '16GB', 'storage': '128GB', 'battery': '4700mAh', 'camera': '50MP Triple',  'image_url': IMG['google'],  'description': 'Compact Pro flagship. Tensor G4, stunning 6.3-inch LTPO OLED, and the best computational photography available.'},
            {'category': categories['Flagship'], 'brand': 'Google',  'name': 'Pixel 9',              'model': '9',             'price':  799.99, 'stock': 25, 'ram': '12GB', 'storage': '128GB', 'battery': '4700mAh', 'camera': '50MP Dual',    'image_url': IMG['google'],  'description': 'Pure Android flagship experience. Tensor G4 chip, 6.3-inch Actua display, and guaranteed 7 years of updates.'},
            {'category': categories['Flagship'], 'brand': 'OnePlus', 'name': 'OnePlus 13',           'model': '13',            'price':  899.99, 'stock': 20, 'ram': '12GB', 'storage': '256GB', 'battery': '6000mAh', 'camera': '50MP Triple',  'image_url': IMG['oneplus'], 'description': 'Flagship killer redefined. Snapdragon 8 Elite, Hasselblad-tuned triple cameras, 100W SUPERVOOC charging.'},
            {'category': categories['Flagship'], 'brand': 'OnePlus', 'name': 'OnePlus 12',           'model': '12',            'price':  799.99, 'stock': 15, 'ram': '12GB', 'storage': '256GB', 'battery': '5400mAh', 'camera': '50MP Triple',  'image_url': IMG['oneplus'], 'description': 'Previous-gen flagship. Snapdragon 8 Gen 3, Hasselblad cameras, 100W wired + 50W wireless charging.'},
            {'category': categories['Flagship'], 'brand': 'Xiaomi',  'name': 'Xiaomi 14 Ultra',      'model': '14 Ultra',      'price': 1099.99, 'stock': 12, 'ram': '16GB', 'storage': '512GB', 'battery': '5300mAh', 'camera': '50MP Quad',    'image_url': IMG['xiaomi'],  'description': 'Photography powerhouse co-engineered with Leica. Four Leica Summilux lenses, Snapdragon 8 Gen 3, and 90W HyperCharge.'},
            {'category': categories['Flagship'], 'brand': 'Xiaomi',  'name': 'Xiaomi 14',            'model': '14',            'price':  799.99, 'stock': 18, 'ram': '12GB', 'storage': '256GB', 'battery': '4610mAh', 'camera': '50MP Triple',  'image_url': IMG['xiaomi'],  'description': 'Compact flagship with Leica optics. Snapdragon 8 Gen 3, ceramic back, and blazing 90W charging speed.'},
            {'category': categories['Flagship'], 'brand': 'Sony',    'name': 'Xperia 1 VI',          'model': 'Xperia 1 VI',   'price': 1299.99, 'stock':  8, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '48MP Triple',  'image_url': IMG['generic'], 'description': 'Creator\'s dream phone. 4K HDR OLED display, Zeiss optics with real telephoto zoom, 4K 120fps video recording.'},
            {'category': categories['Flagship'], 'brand': 'Sony',    'name': 'Xperia 5 VI',          'model': 'Xperia 5 VI',   'price':  999.99, 'stock': 10, 'ram': '8GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '48MP Triple',  'image_url': IMG['generic'], 'description': 'Compact powerhouse with Zeiss optics. 21:9 OLED display, IP68 rating, 3.5mm jack, and a dedicated shutter button.'},
            {'category': categories['Flagship'], 'brand': 'Huawei',  'name': 'Pura 70 Ultra',        'model': 'Pura 70 Ultra', 'price': 1199.99, 'stock':  6, 'ram': '16GB', 'storage': '512GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['generic2'],'description': 'Huawei\'s finest. Kirin 9010 chip, retractable variable aperture camera, satellite messaging support, and luxurious design.'},
            {'category': categories['Flagship'], 'brand': 'vivo',    'name': 'vivo X200 Pro',        'model': 'X200 Pro',      'price': 1049.99, 'stock': 10, 'ram': '16GB', 'storage': '512GB', 'battery': '6000mAh', 'camera': '50MP Triple',  'image_url': IMG['generic3'],'description': 'Zeiss-partnered flagship. Dimensity 9400, massive 6000mAh battery, and exceptional low-light photography.'},
            {'category': categories['Flagship'], 'brand': 'OPPO',    'name': 'Find X8 Pro',          'model': 'Find X8 Pro',   'price': 1099.99, 'stock':  9, 'ram': '16GB', 'storage': '256GB', 'battery': '5910mAh', 'camera': '50MP Quad',    'image_url': IMG['generic2'],'description': 'Hasselblad-powered quad camera, Dimensity 9400, IP69 waterproofing, and ultra-fast 80W wireless charging.'},

            {'category': categories['Mid-Range'], 'brand': 'Apple',   'name': 'iPhone 16',           'model': '16',            'price':  799.99, 'stock': 50, 'ram': '8GB',  'storage': '128GB', 'battery': '3561mAh', 'camera': '48MP Dual',    'image_url': IMG['apple'],   'description': 'The standard iPhone 16. A18 chip, Action Button, Camera Control button, and next-generation portrait photography.'},
            {'category': categories['Mid-Range'], 'brand': 'Apple',   'name': 'iPhone 16 Plus',      'model': '16 Plus',       'price':  899.99, 'stock': 35, 'ram': '8GB',  'storage': '128GB', 'battery': '4674mAh', 'camera': '48MP Dual',    'image_url': IMG['apple2'],  'description': 'Big-screen value. A18 chip, 6.7-inch display, longest battery life in an iPhone, and all-day performance.'},
            {'category': categories['Mid-Range'], 'brand': 'Apple',   'name': 'iPhone 15',           'model': '15',            'price':  699.99, 'stock': 40, 'ram': '6GB',  'storage': '128GB', 'battery': '3349mAh', 'camera': '48MP Dual',    'image_url': IMG['apple3'],  'description': 'Dynamic Island, A16 Bionic chip, 48MP main camera, and USB-C connectivity. Still a powerhouse.'},
            {'category': categories['Mid-Range'], 'brand': 'Samsung', 'name': 'Galaxy A55',          'model': 'A55',           'price':  449.99, 'stock': 60, 'ram': '8GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung2'],'description': 'Premium mid-ranger. IP67 rating, 50MP OIS main camera, 6.6-inch Super AMOLED, and 25W fast charging.'},
            {'category': categories['Mid-Range'], 'brand': 'Samsung', 'name': 'Galaxy A35',          'model': 'A35',           'price':  349.99, 'stock': 70, 'ram': '6GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung3'],'description': 'Stylish mid-range with IP67 rating, 50MP camera, 6.6-inch Super AMOLED display, and 5 years of OS updates.'},
            {'category': categories['Mid-Range'], 'brand': 'Samsung', 'name': 'Galaxy A54',          'model': 'A54',           'price':  349.99, 'stock': 45, 'ram': '8GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung4'],'description': 'Last-gen A-series favorite. 50MP OIS camera, IP67 waterproofing, and a silky 120Hz Super AMOLED display.'},
            {'category': categories['Mid-Range'], 'brand': 'Google',  'name': 'Pixel 8a',            'model': '8a',            'price':  499.99, 'stock': 30, 'ram': '8GB',  'storage': '128GB', 'battery': '4492mAh', 'camera': '64MP Dual',    'image_url': IMG['google'],  'description': 'Best mid-range camera phone. Tensor G3 chip, 64MP main camera, IP67, and 7 years of OS + security updates.'},
            {'category': categories['Mid-Range'], 'brand': 'Google',  'name': 'Pixel 7a',            'model': '7a',            'price':  349.99, 'stock': 25, 'ram': '8GB',  'storage': '128GB', 'battery': '4385mAh', 'camera': '64MP Dual',    'image_url': IMG['google'],  'description': 'Previous-gen A-series bargain. Tensor G2 chip, 64MP camera, wireless charging, and a 90Hz OLED display.'},
            {'category': categories['Mid-Range'], 'brand': 'OnePlus', 'name': 'OnePlus Nord 4',      'model': 'Nord 4',        'price':  499.99, 'stock': 35, 'ram': '12GB', 'storage': '256GB', 'battery': '5500mAh', 'camera': '50MP Dual',    'image_url': IMG['oneplus'], 'description': 'Metal unibody mid-ranger. Snapdragon 7+ Gen 3, 5500mAh battery, 100W SUPERVOOC, and a 120Hz AMOLED display.'},
            {'category': categories['Mid-Range'], 'brand': 'OnePlus', 'name': 'OnePlus Nord CE 4',   'model': 'Nord CE 4',     'price':  349.99, 'stock': 40, 'ram': '8GB',  'storage': '256GB', 'battery': '5500mAh', 'camera': '50MP Dual',    'image_url': IMG['oneplus'], 'description': 'Value-packed mid-ranger. Snapdragon 7s Gen 3, 100W charging, and a bright 6.7-inch AMOLED display.'},
            {'category': categories['Mid-Range'], 'brand': 'Xiaomi',  'name': 'Xiaomi 13T',          'model': '13T',           'price':  549.99, 'stock': 30, 'ram': '8GB',  'storage': '256GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['xiaomi'],  'description': 'Leica cameras at a mid-range price. Dimensity 8200 Ultra, 144Hz AMOLED, and 67W TurboCharge.'},
            {'category': categories['Mid-Range'], 'brand': 'Xiaomi',  'name': 'Xiaomi 13T Pro',      'model': '13T Pro',       'price':  699.99, 'stock': 25, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['xiaomi'],  'description': 'Pro mid-ranger with Leica cameras. Dimensity 9200+, 144Hz AMOLED, and blazing 120W HyperCharge.'},
            {'category': categories['Mid-Range'], 'brand': 'Motorola','name': 'Moto G Power 5G',     'model': 'G Power 5G',    'price':  299.99, 'stock': 55, 'ram': '8GB',  'storage': '256GB', 'battery': '6000mAh', 'camera': '50MP Triple',  'image_url': IMG['generic'], 'description': 'Battery champion. Massive 6000mAh cell, 30W charging, Snapdragon 695 5G, and a clean Android experience.'},
            {'category': categories['Mid-Range'], 'brand': 'Motorola','name': 'Edge 50 Pro',         'model': 'Edge 50 Pro',   'price':  499.99, 'stock': 30, 'ram': '12GB', 'storage': '256GB', 'battery': '4500mAh', 'camera': '50MP Triple',  'image_url': IMG['generic'], 'description': 'Stylish mid-ranger with curved pOLED display, Snapdragon 7s Gen 2, IP68 rating, and 125W TurboPower charging.'},
            {'category': categories['Mid-Range'], 'brand': 'Nothing', 'name': 'Phone (2a)',           'model': 'Phone (2a)',    'price':  349.99, 'stock': 28, 'ram': '8GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Dual',    'image_url': IMG['generic2'],'description': 'Iconic transparent design with Glyph Interface. Dimensity 7200 Pro, 50MP Sony cameras, and 45W fast charging.'},
            {'category': categories['Mid-Range'], 'brand': 'Nothing', 'name': 'Phone (2)',            'model': 'Phone (2)',     'price':  499.99, 'stock': 22, 'ram': '12GB', 'storage': '256GB', 'battery': '4700mAh', 'camera': '50MP Dual',    'image_url': IMG['generic2'],'description': 'Refined transparent design. Snapdragon 8+ Gen 1, expanded Glyph Interface, 120Hz LTPO OLED, and Android 15.'},
            {'category': categories['Mid-Range'], 'brand': 'Realme',  'name': 'GT 6',                'model': 'GT 6',          'price':  499.99, 'stock': 25, 'ram': '12GB', 'storage': '256GB', 'battery': '5500mAh', 'camera': '50MP Triple',  'image_url': IMG['generic3'],'description': 'Performance mid-ranger. Snapdragon 8s Gen 3, 120Hz AMOLED, 100W SUPERVOOC charging, and AI-enhanced cameras.'},
            {'category': categories['Mid-Range'], 'brand': 'Realme',  'name': 'GT 5 Pro',            'model': 'GT 5 Pro',      'price':  549.99, 'stock': 20, 'ram': '16GB', 'storage': '256GB', 'battery': '5400mAh', 'camera': '50MP Triple',  'image_url': IMG['generic3'],'description': 'Flagship features, mid-range pricing. Snapdragon 8 Gen 3, periscope telephoto, 100W + 50W wireless charging.'},
            {'category': categories['Mid-Range'], 'brand': 'OPPO',    'name': 'Reno 12 Pro',         'model': 'Reno 12 Pro',   'price':  499.99, 'stock': 22, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['generic2'],'description': 'AI photography focused mid-ranger. Dimensity 9200+, 6.7-inch AMOLED, 80W SUPERVOOC, and vegan leather finish.'},
            {'category': categories['Mid-Range'], 'brand': 'Honor',   'name': 'Magic 6 Pro',         'model': 'Magic 6 Pro',   'price':  799.99, 'stock': 15, 'ram': '12GB', 'storage': '512GB', 'battery': '5600mAh', 'camera': '50MP Triple',  'image_url': IMG['generic3'],'description': 'Exceptional battery life and cameras. Snapdragon 8 Gen 3, Eye of the God camera module, and ultra-fast charging.'},
            {'category': categories['Mid-Range'], 'brand': 'Honor',   'name': 'Magic 6 Lite',        'model': 'Magic 6 Lite',  'price':  299.99, 'stock': 40, 'ram': '8GB',  'storage': '256GB', 'battery': '5300mAh', 'camera': '108MP Triple', 'image_url': IMG['generic3'],'description': 'Value mid-ranger with 108MP camera, Snapdragon 6 Gen 1, and a massive 5300mAh battery with solid daily performance.'},

            {'category': categories['Budget'], 'brand': 'Apple',    'name': 'iPhone SE (3rd Gen)',  'model': 'SE 3rd Gen',    'price':  429.99, 'stock': 45, 'ram': '4GB',  'storage': '64GB',  'battery': '2018mAh', 'camera': '12MP Single',  'image_url': IMG['apple3'],  'description': 'Most affordable iPhone. A15 Bionic chip, Touch ID, 5G connectivity, and classic iPhone design in a compact body.'},
            {'category': categories['Budget'], 'brand': 'Samsung',  'name': 'Galaxy A25',           'model': 'A25',           'price':  249.99, 'stock': 80, 'ram': '6GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung2'],'description': 'Solid budget phone. Exynos 1280, 50MP camera, 6.5-inch Super AMOLED display, and 25W fast charging.'},
            {'category': categories['Budget'], 'brand': 'Samsung',  'name': 'Galaxy A15',           'model': 'A15',           'price':  149.99, 'stock': 90, 'ram': '4GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung3'],'description': 'Entry-level Samsung reliability. 50MP camera, 90Hz Super AMOLED display, and long-lasting 5000mAh battery.'},
            {'category': categories['Budget'], 'brand': 'Samsung',  'name': 'Galaxy A05s',          'model': 'A05s',          'price':   99.99, 'stock':100, 'ram': '4GB',  'storage': '64GB',  'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung4'],'description': 'Ultra-affordable Samsung. 50MP main camera, Snapdragon 680, 5000mAh battery, and dependable everyday performance.'},
            {'category': categories['Budget'], 'brand': 'Xiaomi',   'name': 'Redmi Note 13',        'model': 'Note 13',       'price':  199.99, 'stock':100, 'ram': '8GB',  'storage': '256GB', 'battery': '5000mAh', 'camera': '200MP Triple', 'image_url': IMG['xiaomi'],  'description': 'Incredible value. 200MP flagship-grade camera, AMOLED display, Snapdragon 685, and up to 256GB storage.'},
            {'category': categories['Budget'], 'brand': 'Xiaomi',   'name': 'Redmi Note 13 Pro',    'model': 'Note 13 Pro',   'price':  279.99, 'stock': 75, 'ram': '8GB',  'storage': '256GB', 'battery': '5100mAh', 'camera': '200MP Triple', 'image_url': IMG['xiaomi'],  'description': 'Pro budget camera. 200MP OIS sensor, Snapdragon 7s Gen 2, 120Hz AMOLED, and 67W TurboCharge.'},
            {'category': categories['Budget'], 'brand': 'Xiaomi',   'name': 'Redmi 13C',            'model': 'Redmi 13C',     'price':  129.99, 'stock': 90, 'ram': '4GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['xiaomi'],  'description': 'Most affordable Redmi. MediaTek Helio G85, 50MP camera, 5000mAh battery, and fingerprint sensor on side.'},
            {'category': categories['Budget'], 'brand': 'Xiaomi',   'name': 'POCO M6 Pro',          'model': 'POCO M6 Pro',   'price':  219.99, 'stock': 65, 'ram': '8GB',  'storage': '256GB', 'battery': '5000mAh', 'camera': '64MP Triple',  'image_url': IMG['xiaomi'],  'description': 'Performance per dollar king. Helio G99 Ultra, 64MP camera, 120Hz AMOLED display, and 67W turbo charging.'},
            {'category': categories['Budget'], 'brand': 'Xiaomi',   'name': 'POCO X6 Pro',          'model': 'POCO X6 Pro',   'price':  349.99, 'stock': 55, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '64MP Triple',  'image_url': IMG['xiaomi'],  'description': 'Budget flagship fighter. Dimensity 8300 Ultra, 64MP camera, 120Hz AMOLED, and 67W HyperCharge.'},
            {'category': categories['Budget'], 'brand': 'Motorola', 'name': 'Moto G84',             'model': 'Moto G84',      'price':  199.99, 'stock': 70, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '50MP Dual',    'image_url': IMG['generic'], 'description': 'Premium-feeling budget pick. pOLED display, Snapdragon 695, 50MP camera with OIS, and 30W TurboPower charging.'},
            {'category': categories['Budget'], 'brand': 'Motorola', 'name': 'Moto G54',             'model': 'Moto G54',      'price':  149.99, 'stock': 80, 'ram': '8GB',  'storage': '256GB', 'battery': '6000mAh', 'camera': '50MP Dual',    'image_url': IMG['generic'], 'description': 'Battery monster on a budget. Dimensity 7020, 6000mAh battery, 50MP camera, and near-stock Android experience.'},
            {'category': categories['Budget'], 'brand': 'Nokia',    'name': 'Nokia G42 5G',         'model': 'G42 5G',        'price':  199.99, 'stock': 50, 'ram': '6GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['generic2'],'description': 'Repairable by design. Snapdragon 480+ 5G, 50MP camera, user-replaceable battery, and 3 years of Android updates.'},
            {'category': categories['Budget'], 'brand': 'Nokia',    'name': 'Nokia C32',            'model': 'C32',           'price':   99.99, 'stock': 85, 'ram': '4GB',  'storage': '64GB',  'battery': '5000mAh', 'camera': '50MP Dual',    'image_url': IMG['generic2'],'description': 'Entry-level durability. Military-grade tested, 50MP camera, 5000mAh battery, and 2 years of OS updates.'},
            {'category': categories['Budget'], 'brand': 'Realme',   'name': 'Realme C67',           'model': 'C67',           'price':  159.99, 'stock': 75, 'ram': '6GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '108MP Dual',   'image_url': IMG['generic3'],'description': 'High-res camera on a budget. 108MP camera, Snapdragon 685, 6.72-inch FHD+ display, and fast 33W charging.'},
            {'category': categories['Budget'], 'brand': 'Realme',   'name': 'Realme 12',            'model': 'Realme 12',     'price':  219.99, 'stock': 65, 'ram': '8GB',  'storage': '256GB', 'battery': '5000mAh', 'camera': '108MP Triple', 'image_url': IMG['generic3'],'description': 'Style meets value. 108MP periscope portrait camera, MediaTek Helio G99, 120Hz Super AMOLED, and leather-texture design.'},
            {'category': categories['Budget'], 'brand': 'Infinix',  'name': 'Infinix Hot 40 Pro',   'model': 'Hot 40 Pro',    'price':  129.99, 'stock': 90, 'ram': '8GB',  'storage': '256GB', 'battery': '5000mAh', 'camera': '108MP Triple', 'image_url': IMG['generic'],  'description': 'Feature-rich ultra-budget. 108MP camera, Helio G99, 120Hz display, and 45W fast charging at an unbeatable price.'},
            {'category': categories['Budget'], 'brand': 'Tecno',    'name': 'Camon 30 Premier',     'model': 'Camon 30 Prem', 'price':  219.99, 'stock': 55, 'ram': '8GB',  'storage': '256GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['generic2'],'description': 'Portrait photography specialist. Dimensity 8200, 50MP RGBW sensor, 45W charging, and AMOLED display.'},
            {'category': categories['Budget'], 'brand': 'Itel',     'name': 'Itel S24',             'model': 'S24',           'price':   79.99, 'stock':100, 'ram': '4GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '13MP Dual',    'image_url': IMG['generic3'],'description': 'The most affordable option. Basic smartphone features, dual SIM, 5000mAh battery, and a lightweight 179g body.'},

            {'category': categories['Foldable'], 'brand': 'Samsung', 'name': 'Galaxy Z Fold 6',     'model': 'Z Fold 6',      'price': 1899.99, 'stock': 10, 'ram': '12GB', 'storage': '256GB', 'battery': '4400mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung4'],'description': 'The ultimate book-fold phone. Slimmer, lighter design, 7.6-inch inner display, improved hinge, and Snapdragon 8 Gen 3.'},
            {'category': categories['Foldable'], 'brand': 'Samsung', 'name': 'Galaxy Z Fold 5',     'model': 'Z Fold 5',      'price': 1599.99, 'stock':  8, 'ram': '12GB', 'storage': '256GB', 'battery': '4400mAh', 'camera': '50MP Triple',  'image_url': IMG['samsung4'],'description': 'Previous-gen book-fold. Snapdragon 8 Gen 2, 7.6-inch Flex Window, gapless hinge design, and S Pen support.'},
            {'category': categories['Foldable'], 'brand': 'Samsung', 'name': 'Galaxy Z Flip 6',     'model': 'Z Flip 6',      'price': 1099.99, 'stock': 14, 'ram': '12GB', 'storage': '256GB', 'battery': '4000mAh', 'camera': '50MP Dual',    'image_url': IMG['samsung3'],'description': 'Stylish flip foldable. Snapdragon 8 Gen 3, largest cover screen ever, 50MP main camera, and AI-powered features.'},
            {'category': categories['Foldable'], 'brand': 'Samsung', 'name': 'Galaxy Z Flip 5',     'model': 'Z Flip 5',      'price':  899.99, 'stock': 12, 'ram': '8GB',  'storage': '256GB', 'battery': '3700mAh', 'camera': '12MP Dual',    'image_url': IMG['samsung3'],'description': 'Previous-gen flip. Snapdragon 8 Gen 2, large Flex Window cover display, and iconic compact flip form factor.'},
            {'category': categories['Foldable'], 'brand': 'Google',  'name': 'Pixel 9 Pro Fold',    'model': '9 Pro Fold',    'price': 1799.99, 'stock':  7, 'ram': '16GB', 'storage': '256GB', 'battery': '4650mAh', 'camera': '48MP Triple',  'image_url': IMG['google'],  'description': 'Google\'s second foldable. Tensor G4, improved crease-less inner display, Pixel camera magic, and 7 years of updates.'},
            {'category': categories['Foldable'], 'brand': 'OnePlus', 'name': 'OnePlus Open',        'model': 'Open',          'price': 1699.99, 'stock':  9, 'ram': '16GB', 'storage': '512GB', 'battery': '4805mAh', 'camera': '48MP Triple',  'image_url': IMG['oneplus'], 'description': 'Hasselblad foldable cameras, Snapdragon 8 Gen 2, thinnest book-fold hinge, and 67W SUPERVOOC charging.'},
            {'category': categories['Foldable'], 'brand': 'Xiaomi',  'name': 'Mix Fold 4',          'model': 'Mix Fold 4',    'price': 1799.99, 'stock':  6, 'ram': '16GB', 'storage': '512GB', 'battery': '5100mAh', 'camera': '50MP Triple',  'image_url': IMG['xiaomi'],  'description': 'World\'s thinnest book-fold phone. Leica cameras, Snapdragon 8 Gen 3, and razor-thin 9.47mm profile when unfolded.'},
            {'category': categories['Foldable'], 'brand': 'Motorola','name': 'Razr 50 Ultra',       'model': 'Razr 50 Ultra', 'price': 1199.99, 'stock': 10, 'ram': '12GB', 'storage': '512GB', 'battery': '4000mAh', 'camera': '50MP Dual',    'image_url': IMG['generic'], 'description': 'Iconic flip revival. Snapdragon 8s Gen 3, massive 4-inch cover display, 50MP Satellite AI camera, and pTCO OLED panel.'},
            {'category': categories['Foldable'], 'brand': 'Motorola','name': 'Razr 50',             'model': 'Razr 50',       'price':  799.99, 'stock': 12, 'ram': '8GB',  'storage': '256GB', 'battery': '4200mAh', 'camera': '50MP Dual',    'image_url': IMG['generic'], 'description': 'Affordable flip foldable. Dimensity 7300X, large cover display, 50MP camera, and classic Razr design.'},
            {'category': categories['Foldable'], 'brand': 'Honor',   'name': 'Magic V3',            'model': 'Magic V3',      'price': 1899.99, 'stock':  5, 'ram': '16GB', 'storage': '512GB', 'battery': '5150mAh', 'camera': '50MP Triple',  'image_url': IMG['generic3'],'description': 'World\'s slimmest large foldable. Snapdragon 8 Gen 3, only 9.2mm unfolded, 5150mAh battery, and silicon-carbon tech.'},
            {'category': categories['Foldable'], 'brand': 'vivo',    'name': 'X Fold 3 Pro',        'model': 'X Fold 3 Pro',  'price': 1799.99, 'stock':  6, 'ram': '16GB', 'storage': '512GB', 'battery': '5700mAh', 'camera': '50MP Triple',  'image_url': IMG['generic2'],'description': 'Zeiss optics meet foldable tech. Snapdragon 8 Gen 3, IP68 rating, 100W charging, and best-in-class hinge durability.'},

            {'category': categories['Gaming'], 'brand': 'ASUS',     'name': 'ROG Phone 8 Pro',      'model': 'ROG 8 Pro',     'price': 1299.99, 'stock': 12, 'ram': '16GB', 'storage': '512GB', 'battery': '5500mAh', 'camera': '50MP Triple',  'image_url': IMG['gaming'],  'description': 'Ultimate gaming flagship. Snapdragon 8 Gen 3, 165Hz AMOLED, AeroActive Cooler, dual USB-C, and Aura RGB lighting.'},
            {'category': categories['Gaming'], 'brand': 'ASUS',     'name': 'ROG Phone 8',          'model': 'ROG 8',         'price':  999.99, 'stock': 15, 'ram': '12GB', 'storage': '256GB', 'battery': '5500mAh', 'camera': '50MP Triple',  'image_url': IMG['gaming'],  'description': 'Gaming powerhouse. Snapdragon 8 Gen 3, 165Hz display, GameCool 8 cooling system, and ultra-sonic shoulder triggers.'},
            {'category': categories['Gaming'], 'brand': 'ASUS',     'name': 'ROG Phone 7 Ultimate', 'model': 'ROG 7 Ultimate','price':  899.99, 'stock': 10, 'ram': '16GB', 'storage': '512GB', 'battery': '6000mAh', 'camera': '50MP Triple',  'image_url': IMG['gaming'],  'description': 'Previous-gen gaming beast. Snapdragon 8 Gen 2, 165Hz AMOLED, AeroActive Cooler 7, secondary display on back.'},
            {'category': categories['Gaming'], 'brand': 'Xiaomi',   'name': 'Black Shark 5 Pro',    'model': 'BS 5 Pro',      'price':  699.99, 'stock': 18, 'ram': '12GB', 'storage': '256GB', 'battery': '4650mAh', 'camera': '108MP Triple', 'image_url': IMG['gaming'],  'description': 'Competitive gaming phone. Snapdragon 8 Gen 1, pop-up shoulder triggers, 144Hz AMOLED, and RGB strip lighting.'},
            {'category': categories['Gaming'], 'brand': 'Nubia',    'name': 'RedMagic 9 Pro',       'model': 'RedMagic 9 Pro','price':  799.99, 'stock': 14, 'ram': '16GB', 'storage': '512GB', 'battery': '6500mAh', 'camera': '50MP Triple',  'image_url': IMG['gaming'],  'description': 'Cooling-focused gaming phone. Snapdragon 8 Gen 3, built-in fan + vapor chamber, 185Hz display, and 165W charging.'},
            {'category': categories['Gaming'], 'brand': 'Nubia',    'name': 'RedMagic 8 Pro',       'model': 'RedMagic 8 Pro','price':  649.99, 'stock': 12, 'ram': '16GB', 'storage': '256GB', 'battery': '6000mAh', 'camera': '50MP Triple',  'image_url': IMG['gaming'],  'description': 'Under-display camera gaming phone. Snapdragon 8 Gen 2, built-in turbo fan, 120W fast charging, and ICE Magic cooling.'},
            {'category': categories['Gaming'], 'brand': 'Lenovo',   'name': 'Legion Phone 3 Pro',   'model': 'Legion 3 Pro',  'price':  799.99, 'stock': 10, 'ram': '16GB', 'storage': '512GB', 'battery': '5000mAh', 'camera': '64MP Triple',  'image_url': IMG['gaming'],  'description': 'Esports-grade gaming. Snapdragon 8 Gen 2, twin pop-up triggers, dual USB-C ports, active fan cooling, 144Hz display.'},
            {'category': categories['Gaming'], 'brand': 'Samsung',  'name': 'Galaxy S24 FE Gaming', 'model': 'S24 FE Gaming', 'price':  649.99, 'stock': 20, 'ram': '8GB',  'storage': '256GB', 'battery': '4700mAh', 'camera': '50MP Triple',  'image_url': IMG['gaming'],  'description': 'Mainstream gaming experience. Exynos 2500, 120Hz Super AMOLED, Game Booster Pro, and vapour cooling chamber.'},

            {'category': categories['Rugged'], 'brand': 'CAT',      'name': 'CAT S75',              'model': 'S75',           'price':  649.99, 'stock': 15, 'ram': '6GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '50MP Triple',  'image_url': IMG['rugged'],  'description': 'Built for the toughest jobs. MIL-SPEC 810H, IP68+IP69K, built-in satellite messaging, and thermal camera.'},
            {'category': categories['Rugged'], 'brand': 'CAT',      'name': 'CAT S62 Pro',          'model': 'S62 Pro',       'price':  549.99, 'stock': 12, 'ram': '6GB',  'storage': '128GB', 'battery': '4000mAh', 'camera': '12MP Dual',    'image_url': IMG['rugged'],  'description': 'Professional rugged phone. FLIR thermal camera, MIL-SPEC 810H, IP68/IP69K, and Snapdragon 660 processor.'},
            {'category': categories['Rugged'], 'brand': 'Doogee',   'name': 'Doogee S110',          'model': 'S110',          'price':  399.99, 'stock': 20, 'ram': '12GB', 'storage': '256GB', 'battery': '10800mAh','camera': '108MP Triple', 'image_url': IMG['rugged'],  'description': 'Massive rugged battery phone. 10800mAh battery, 66W charging, 108MP camera, IP68+IP69K, and NFC support.'},
            {'category': categories['Rugged'], 'brand': 'Doogee',   'name': 'Doogee V30T',          'model': 'V30T',          'price':  299.99, 'stock': 25, 'ram': '12GB', 'storage': '256GB', 'battery': '10800mAh','camera': '64MP Triple',  'image_url': IMG['rugged'],  'description': 'Budget rugged powerhouse. 10800mAh battery, Dimensity 1080, 64MP camera, and military-grade durability certification.'},
            {'category': categories['Rugged'], 'brand': 'Ulefone',  'name': 'Armor 23 Ultra',       'model': 'Armor 23 Ultra','price':  449.99, 'stock': 18, 'ram': '12GB', 'storage': '256GB', 'battery': '13200mAh','camera': '200MP Triple', 'image_url': IMG['rugged'],  'description': 'Extreme battery rugged phone. 13200mAh battery, 200MP camera, thermal sensor, satellite messaging, IP68/IP69K.'},
            {'category': categories['Rugged'], 'brand': 'Ulefone',  'name': 'Power Armor 19T',      'model': 'Armor 19T',     'price':  349.99, 'stock': 22, 'ram': '12GB', 'storage': '256GB', 'battery': '9600mAh', 'camera': '64MP Triple',  'image_url': IMG['rugged'],  'description': 'Night vision rugged phone. Sony IMX586 night vision camera, 9600mAh battery, Dimensity 900, and IP68 protection.'},
            {'category': categories['Rugged'], 'brand': 'Blackview', 'name': 'BL9000 Pro',          'model': 'BL9000 Pro',    'price':  499.99, 'stock': 14, 'ram': '12GB', 'storage': '256GB', 'battery': '8800mAh', 'camera': '50MP Triple',  'image_url': IMG['rugged'],  'description': 'Premium rugged with 5G. Dimensity 8050, built-in thermal camera, 8800mAh battery, 120W charging, and IP68/IP69K.'},
            {'category': categories['Rugged'], 'brand': 'Blackview', 'name': 'BV9300 Pro',          'model': 'BV9300 Pro',    'price':  329.99, 'stock': 20, 'ram': '12GB', 'storage': '256GB', 'battery': '15080mAh','camera': '50MP Triple',  'image_url': IMG['rugged'],  'description': 'Absolute battery endurance champion. 15080mAh battery, built-in LED floodlight, Helio G99, and IP68 waterproofing.'},
            {'category': categories['Rugged'], 'brand': 'Kyocera',  'name': 'DuraForce Ultra 5G',   'model': 'DuraForce 5G',  'price':  549.99, 'stock': 10, 'ram': '6GB',  'storage': '128GB', 'battery': '4500mAh', 'camera': '12MP Triple',  'image_url': IMG['rugged'],  'description': 'US military-grade certified rugged. MIL-SPEC 810H, IP68, push-to-talk support, Snapdragon 778G, and 5G connectivity.'},
            {'category': categories['Rugged'], 'brand': 'Sonim',    'name': 'XP10',                 'model': 'XP10',          'price':  399.99, 'stock': 12, 'ram': '4GB',  'storage': '64GB',  'battery': '4900mAh', 'camera': '48MP Dual',    'image_url': IMG['rugged'],  'description': 'Enterprise rugged for field workers. IP69K, MIL-SPEC 810H, push-to-talk, bar code scanner support, and loud 109dB speaker.'},


            {'category': categories['Flagship'], 'brand': 'Samsung', 'name': 'Galaxy S23 Ultra',     'model': 'S23 Ultra',     'price':  849.99, 'stock': 12, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '200MP Quad',   'image_url': IMG['samsung'],  'description': 'Proven Ultra flagship. Snapdragon 8 Gen 2, integrated S Pen, 200MP quad camera, and 6.8-inch Dynamic AMOLED 2X.'},
            {'category': categories['Flagship'], 'brand': 'Apple',   'name': 'iPhone 14 Pro Max',    'model': '14 Pro Max',    'price':  799.99, 'stock': 10, 'ram': '6GB',  'storage': '128GB', 'battery': '4323mAh', 'camera': '48MP Triple',  'image_url': IMG['apple'],    'description': 'Still a powerhouse. A16 Bionic, Dynamic Island, Always-On display, 48MP main camera, and ProRes video recording.'},
            {'category': categories['Mid-Range'], 'brand': 'Motorola','name': 'Moto Edge 50 Fusion', 'model': 'Edge 50 Fusion', 'price':  299.99, 'stock': 45, 'ram': '8GB',  'storage': '256GB', 'battery': '5000mAh', 'camera': '50MP Dual',    'image_url': IMG['generic'],  'description': 'Curved pOLED mid-ranger. Snapdragon 7s Gen 2, 68W TurboPower, 50MP OIS camera, and ultra-slim 7.9mm design.'},
            {'category': categories['Mid-Range'], 'brand': 'Realme',  'name': 'Realme GT Neo 6',     'model': 'GT Neo 6',      'price':  399.99, 'stock': 32, 'ram': '12GB', 'storage': '256GB', 'battery': '6500mAh', 'camera': '50MP Dual',    'image_url': IMG['generic3'], 'description': 'Performance bargain. Snapdragon 7+ Gen 3, massive 6500mAh battery, 120W charging, and 120Hz AMOLED display.'},
            {'category': categories['Budget'], 'brand': 'Xiaomi',    'name': 'POCO F6',              'model': 'POCO F6',       'price':  299.99, 'stock': 60, 'ram': '12GB', 'storage': '256GB', 'battery': '4500mAh', 'camera': '50MP Dual',    'image_url': IMG['xiaomi'],   'description': 'Budget flagship chip. Snapdragon 8s Gen 3, 120Hz AMOLED, 90W TurboCharge, and OIS-stabilized 50MP main sensor.'},
            {'category': categories['Budget'], 'brand': 'Infinix',   'name': 'Zero 40 5G',           'model': 'Zero 40 5G',   'price':  249.99, 'stock': 55, 'ram': '12GB', 'storage': '256GB', 'battery': '5000mAh', 'camera': '108MP Triple', 'image_url': IMG['generic'],   'description': 'Budget 5G champ. Dimensity 8020, 108MP triple camera, 45W fast charge, 144Hz AMOLED display.'},
            {'category': categories['Gaming'],  'brand': 'ASUS',     'name': 'ROG Phone 6 Pro',      'model': 'ROG 6 Pro',     'price':  799.99, 'stock': 10, 'ram': '18GB', 'storage': '512GB', 'battery': '6000mAh', 'camera': '50MP Triple',  'image_url': IMG['gaming'],   'description': 'Gaming legend. Snapdragon 8+ Gen 1, 165Hz AMOLED, AeroActive Cooler 6, dual USB-C, and customizable RGB elements.'},
            {'category': categories['Rugged'],  'brand': 'AGM',      'name': 'AGM H6 Pro',           'model': 'H6 Pro',        'price':  279.99, 'stock': 18, 'ram': '8GB',  'storage': '128GB', 'battery': '8000mAh', 'camera': '64MP Triple',  'image_url': IMG['rugged'],   'description': 'Affordable rugged with big battery. 8000mAh, 64MP triple camera, IP68/IP69K, Helio G85, and loud dual speakers.'},
            {'category': categories['Foldable'], 'brand': 'Huawei',  'name': 'Mate X5',              'model': 'Mate X5',       'price': 2199.99, 'stock':  4, 'ram': '16GB', 'storage': '512GB', 'battery': '5060mAh', 'camera': '50MP Triple',  'image_url': IMG['generic2'], 'description': 'Premium Huawei foldable. Kirin 9010 chip, outward-folding design, silky OLED panels, and multi-layer HingeGo mechanism.'},
            {'category': categories['Mid-Range'], 'brand': 'Honor',  'name': 'Honor 200 Pro',        'model': 'Honor 200 Pro', 'price':  599.99, 'stock': 20, 'ram': '12GB', 'storage': '512GB', 'battery': '5200mAh', 'camera': '50MP Triple',  'image_url': IMG['generic3'], 'description': 'Portrait king. Snapdragon 8s Gen 3, Harcourt Studio portrait lighting, 5200mAh silicon battery, and 100W charging.'},
            {'category': categories['Budget'],  'brand': 'Nokia',    'name': 'Nokia XR21',           'model': 'XR21',          'price':  449.99, 'stock': 30, 'ram': '6GB',  'storage': '128GB', 'battery': '4800mAh', 'camera': '64MP Dual',    'image_url': IMG['generic2'], 'description': 'Rugged-lite budget phone. MIL-SPEC 810H, IP68, Snapdragon 695, 64MP camera, and 3 years OS + 4 years security updates.'},
            {'category': categories['Mid-Range'], 'brand': 'Sony',   'name': 'Xperia 10 VI',         'model': 'Xperia 10 VI',  'price':  499.99, 'stock': 25, 'ram': '6GB',  'storage': '128GB', 'battery': '5000mAh', 'camera': '48MP Dual',    'image_url': IMG['generic'],  'description': 'Compact Sony mid-ranger. 21:9 OLED display, Snapdragon 6 Gen 1, IP68, 3.5mm headphone jack, and 30W charging.'},
            {'category': categories['Flagship'], 'brand': 'vivo',    'name': 'vivo X100 Pro',        'model': 'X100 Pro',      'price':  999.99, 'stock': 11, 'ram': '16GB', 'storage': '256GB', 'battery': '5400mAh', 'camera': '50MP Triple',  'image_url': IMG['generic3'], 'description': 'Zeiss APO telephoto lens, Dimensity 9300, 100W FlashCharge, and 50W wireless charging in a stunning glass design.'},
        ]

        created = 0
        skipped = 0
        for data in phones_data:
            _, was_created = Phone.objects.get_or_create(
                name=data['name'],
                brand=data['brand'],
                defaults=data
            )
            if was_created:
                created += 1
            else:
                skipped += 1

        self.stdout.write(self.style.SUCCESS(
            f'Done! Created {created} phones, skipped {skipped} existing. '
            f'Total in DB: {Phone.objects.count()} phones across {Category.objects.count()} categories.'
        ))